const principal = [
'3MI,', 
'AIM,', 
'AKI,', 
'ALK,',  
'API,', 
'ARM,',  
'ASP,', 
'ATR,',  
'AWI,', 
'BDF,', 
'BKK,', 
'BSJ,',  
'CAV,', 
'CFG,',  
'CFI,', 
'CFL,',  
'CGR,', 
'CKG,', 
'CMI,', 
'CMU,',  
'CPL,', 
'CPR,',  
'CPV,', 
'CVT,', 
'DBR,', 
'DBT,', 
'DJI,', 
'DLQ,',  
'DOF,', 
'DSI,',  
'EGI,', 
'ETH,',  
'FFI,', 
'FFJ,', 
'FOD,', 
'GAR,',  
'GCC,', 
'GLE,',  
'GLT,', 
'GRM,',  
'GTK,', 
'GTS,', 
'HAI,', 
'HBL,',  
'HLS,', 
'HNI,',  
'HNZ,', 
'HRJ,',   
'IAS,', 
'IBN,', 
'ICR,', 
'IFS,',  
'IMM,', 
'ISW,',  
'JCA,', 
'JHH,',  
'KDT,', 
'KEK,', 
'KFI,', 
'KLF,',  
'KNI,', 
'KPG,',  
'KUI,', 
'MGI,',  
'MIT,', 
'MJI,', 
'MMC,', 
'MMM,',  
'MPM,', 
'MSI,',  
'MSM,', 
'NDL,', 
'NFI,', 
'OFC,', 
'OGB,', 
'OKG,',  
'OKT,', 
'OOT,',  
'OTC,', 
'PGC,',  
'PHI,', 
'PLK,', 
'PMI,', 
'PNG,',  
'PPC,', 
'PPM,',  
'PRE,', 
'PRO,',  
'PVM,', 
'PZC,', 
'RBH,', 
'RBI,',  
'RBT,', 
'RHY,',  
'SCH,', 
'SCJ,', 
'SFI,', 
'SFX,',  
'SMP,', 
'SSS,', 
'STG,', 
'STT,', 
'TGM,', 
'TOI,',  
'TRN,', 
'TSI,',  
'UJM,', 
'UMI,',  
'UNB,', 
'VET,', 
'VIS,', 
'WAD,',  
'WAR,', 
'WDF,',  
'WGI,', 
'WLA,',  
'YHS\n'
];

const otherArray = [
'PT. BINA SAN PRIMA - Malang\n\n', 
'Keterangan : Tanpa Bonus\n\n', 
'Kasifikasi Faktur : ', 
'Tanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n',  
'\nHal. 2\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 3\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 4\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 5\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 6\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 7\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 8\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 9\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 10\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
'\nHal. 11\nTanggal No Faktur Nama Barang Diskon Qty Satuan Jumlah\n', 
];


